apiVersion: v2
appVersion: v10.0
description: A Helm chart for XL Deploy
name: xl-deploy-helmcharts
version: 10.0-GA

dependencies:
- name: haproxy-ingress
  version: 0.9.1
  repository: "https://haproxy-ingress.github.io/charts"
  condition: haproxy-ingress.install

- name: postgresql
  version: 9.8.5
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.install

- name: rabbitmq-ha
  version: 1.47.0
  repository: "https://kubernetes-charts.storage.googleapis.com/"
  condition: rabbitmq-ha.install
